version: '3'

services:
  # api:
  #   build: .
  #   entrypoint: docker-entrypoint.sh
  #   container_name: api
  #   ports:
  #     - '3333:3333'
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     - db
  #     - redis

  db:
    container_name: db
    build: .docker/postgres
    restart: always
    tty: true
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=docker
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - '6379:6379'

